package com.builtbroken.builder.events;

/**
 * Created by Robin Seifert on 6/30/2021.
 */
public enum EventTypes
{
    OBJECT_REGISTERED,
    FILE_LOCATOR_ADDED,
    CONTENT_LOADER_SETUP,
    CONTENT_LOADER_LOAD,
    CONTENT_LOADER_INIT,
    CONTENT_LOADER_LOAD_COMPLETE,
    CONTENT_LOADER_DESTROY,
    CONTENT_LOADER_CLEAN,
    CONTENT_LOADER_FILE_SEARCH,
    CONTENT_LOADER_PROCESS,
    PIPELINE,
    PIPELINE_NODE,
    PIPELINE_OBJECT
}
